### ISSUE TITLE
Prefer an ipv6

### ISSUE THREAD

**Issue by yuanwenliang** [amnezia-vpn/amneziawg-go#33]
Can the AmneziaWG be changed to give priority to ipv6 addresses, or add a setting item to allow users to choose to give priority to ipv6 or ipv4? This is because once AmneziaWG finds an IPv4 address through **DNS**, they will no longer use the IPv6 address, and I hope AmneziaWG can use the **IPv6** address.

**Comment by pokamest** [comment]
amneziawg-go like a wireguard-go doesn't resolve DNS names by itself, it's happening in the client app.
Could you please describe your issue in detail, how to reproduce it?

**Comment by yuanwenliang** [comment]
When I use AmneziaWG as a wireguard client, if the peer information is a domain name plus a port number, after opening a VPN on iOS, the domain name will only be resolved to an IPv4 address. For example, www.xxx.com:1234 will be resolved to 1.2.3.4:1234, and 1.2.3.4 will be used as the server address. But I hope to be able to use the IPv6 address associated with the domain name, like 2000:daf0::1:1234.

**Comment by yuanwenliang** [comment]
https://github.com/amnezia-vpn/awg-apple/blob/09c0fc7f70bdf68f6953ea959d8a18952603fe94/Sources/WireGuardKit/DNSResolver.swift#L81

**Comment by yuanwenliang** [comment]
https://github.com/amnezia-vpn/amneziawg-apple/blob/ef929efeced5bea46f16e6b4404c658995d2c1a9/Sources/WireGuardKit/DNSResolver.swift#L125

**Comment by pokamest** [comment]
so it related to [https://github.com/amnezia-vpn/amneziawg-apple](https://github.com/amnezia-vpn/amneziawg-apple/blob/ef929efeced5bea46f16e6b4404c658995d2c1a9/Sources/WireGuardKit/DNSResolver.swift#L125)

You can open issue in the amneziawg-apple
