### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by marek22k** [amnezia-vpn/amneziawg-go#44]
Hello,

it would be nice if there could be a Debian package for AmeziaWG Go, so that you can simply install it on a server without a container.

Related: https://github.com/amnezia-vpn/amneziawg-tools/issues/19

**Comment by leninalive** [comment]
Hi,

Debian packages are available for kernel module and tools in Launchpad's PPA - https://launchpad.net/~amnezia/+archive/ubuntu/ppa

For Go version we have no plans to build DEB/RPM packages as it is out of Go ideology.

**Comment by marek22k** [comment]
Thanks for the response. Great that there is a deb repo.

However, the packages there all seem to be Ubuntu specific. Could perhaps packages for Debian be added?

**Comment by leninalive** [comment]
You may use Ubuntu packages on Debian as well, all instructions are available in readme [here](https://github.com/amnezia-vpn/amneziawg-linux-kernel-module).

Vanilla WG and AmneziaWG could be used together without any conflicts.

**Comment by marek22k** [comment]
Hi, I have another question and a comment about the Debian package:
It is installed after README in `sources.list`. This should not be, as the file only contains official Debian package sources. Third party software should be in an extra file like `/etc/apt/sources.list.d/amnezia.list`. Furthermore, it is no longer up-to-date to use a global keyring for all packages. Instead, the key should be stored in a separate file `deb [signed-by=/usr/share/keyrings/amnezia.gpg] https://ppa.launchpadcontent.net/amnezia/ppa/ubuntu focal main`.

Furthermore, I cannot find your key: https://keyserver.ubuntu.com/pks/lookup?search=57290828&fingerprint=on&op=index returns `Not Found`. Furthermore, I would recommend not to only provide the key ID, but also the fingerprint to enable verification of the key.
